/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CallbackImport } from './routes/callback'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectIndexImport } from './routes/project/index'
import { Route as ProjectMoodboardImport } from './routes/project/moodboard'

// Create/Update Routes

const CallbackRoute = CallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectIndexRoute = ProjectIndexImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectMoodboardRoute = ProjectMoodboardImport.update({
  id: '/project/moodboard',
  path: '/project/moodboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackImport
      parentRoute: typeof rootRoute
    }
    '/project/moodboard': {
      id: '/project/moodboard'
      path: '/project/moodboard'
      fullPath: '/project/moodboard'
      preLoaderRoute: typeof ProjectMoodboardImport
      parentRoute: typeof rootRoute
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/project/moodboard': typeof ProjectMoodboardRoute
  '/project': typeof ProjectIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/project/moodboard': typeof ProjectMoodboardRoute
  '/project': typeof ProjectIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/project/moodboard': typeof ProjectMoodboardRoute
  '/project/': typeof ProjectIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/callback' | '/project/moodboard' | '/project'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback' | '/project/moodboard' | '/project'
  id: '__root__' | '/' | '/callback' | '/project/moodboard' | '/project/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  ProjectMoodboardRoute: typeof ProjectMoodboardRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  ProjectMoodboardRoute: ProjectMoodboardRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/callback",
        "/project/moodboard",
        "/project/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/callback": {
      "filePath": "callback.tsx"
    },
    "/project/moodboard": {
      "filePath": "project/moodboard.tsx"
    },
    "/project/": {
      "filePath": "project/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
