"""Fix relationships in models

Revision ID: 278df899eefb
Revises: be146425e59c
Create Date: 2025-01-23 17:34:13.069896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278df899eefb'
down_revision = 'be146425e59c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
