"""Fix schema validation issues

Revision ID: 7cefbc4b477d
Revises: cb7f0f8357db
Create Date: 2025-01-23 17:53:17.575839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cefbc4b477d'
down_revision = 'cb7f0f8357db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
