"""Test migration

Revision ID: 7cfb67df97d2
Revises: 
Create Date: 2025-01-05 21:30:08.174018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfb67df97d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moodboard', 'storyline',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('moodboard', 'targetAudience',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('moodboardimage', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('moodboardimage', 'annotation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moodboardimage', 'annotation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('moodboardimage', 'id')
    op.alter_column('moodboard', 'targetAudience',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('moodboard', 'storyline',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
