"""fixed the template, moodboard, project and asset tables

Revision ID: 912d540fd41c
Revises: f22094f0037a
Create Date: 2025-01-21 22:14:26.389888

"""
from alembic import op
from sqlmodel import Field, Column, AutoString
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '912d540fd41c'
down_revision = 'f22094f0037a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('thumbnail_path',
                  AutoString(), nullable=True))
    op.add_column('template', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_column('template', 'template_controls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('template_controls', postgresql.JSON(
        astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('template', 'tags')
    op.drop_column('template', 'thumbnail_path')
    # ### end Alembic commands ###
