"""Rewrote template model

Revision ID: 93d0d194a5a7
Revises: 7cefbc4b477d
Create Date: 2025-02-17 17:37:37.670817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel as sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d0d194a5a7'
down_revision = '7cefbc4b477d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('template_type',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('template', sa.Column(
        'templateData', sa.JSON(), nullable=True))
    op.add_column('template', sa.Column(
        'thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('template', sa.Column(
        'compatible_templates', sa.JSON(), nullable=True))
    op.drop_column('template', 'tags')
    op.drop_column('template', 'description')
    op.drop_column('template', 'thumbnail_path')
    op.drop_column('template', 'price')
    op.drop_column('template', 'minio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column(
        'minio_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('template', sa.Column('price', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=True))
    op.add_column('template', sa.Column('thumbnail_path',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('template', sa.Column(
        'description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('template', sa.Column('tags', postgresql.JSON(
        astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('template', 'compatible_templates')
    op.drop_column('template', 'thumbnail')
    op.drop_column('template', 'templateData')
    op.drop_column('template', 'template_type')
    # ### end Alembic commands ###
