"""Add favorites relationship to Template

Revision ID: cb7f0f8357db
Revises: f888044de42c
Create Date: 2025-01-23 17:46:07.947715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7f0f8357db'
down_revision = 'f888044de42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
