"""Used required id fields for moodboard model

Revision ID: f22094f0037a
Revises: 7cfb67df97d2
Create Date: 2025-01-07 01:35:24.963796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22094f0037a'
down_revision = '7cfb67df97d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
