"""Add favorites relationship to Asset

Revision ID: f888044de42c
Revises: 278df899eefb
Create Date: 2025-01-23 17:39:16.171735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f888044de42c'
down_revision = '278df899eefb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
