import { json } from "@tanstack/start";
import { createAPIFileRoute } from "@tanstack/start/api";

export const APIRoute = createAPIFileRoute("/api/moodboard")({
  // Handle GET requests (autogenerated)
  GET: ({ request, params }) => {
    return json({ message: 'Hello "/moodboard"!' });
  },

  // Add a POST handler for saving moodboard data
  POST: async ({ request }) => {
    try {
      // Parse the FormData from the request
      const formData = await request.formData();

      // Convert FormData to a more usable format
      const moodboardData = {};
      for (const [key, value] of formData.entries()) {
        moodboardData[key] = value;
      }

      // Simulate saving to a database or external service
      console.log("Received moodboard data:", moodboardData);

      // Simulate a delay for processing
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Return a success response
      return json({
        success: true,
        message: "Moodboard saved successfully!",
        data: moodboardData,
      });
    } catch (error) {
      // Handle errors
      console.error("Error saving moodboard:", error);
      return json(
        {
          success: false,
          message: "Failed to save moodboard.",
        },
        { status: 500 }
      );
    }
  },
});
