"""
Internal HMAC-HS256 tokens for Blender service clients.

These tokens are generated by cr8_engine when launching Blender instances
and passed via the CR8_AUTH_TOKEN environment variable. They are NOT Logto
tokens — they are short-lived, internally signed tokens that authenticate
the Blender process back to the Socket.IO server.
"""

import os
import time
import logging

import jwt

logger = logging.getLogger(__name__)


def _get_secret() -> str:
    """Get the internal signing secret."""
    secret = os.environ.get("LOGTO_INTERNAL_SECRET")
    if not secret:
        raise RuntimeError("LOGTO_INTERNAL_SECRET environment variable is not set")
    return secret


def generate_blender_token(username: str, ttl: int = 7200) -> str:
    """
    Generate an HMAC-HS256 signed token for a Blender instance.

    Args:
        username: The cr8 username this Blender instance belongs to.
        ttl: Token time-to-live in seconds (default: 2 hours).

    Returns:
        Encoded JWT string.
    """
    now = int(time.time())
    payload = {
        "sub": username,
        "iss": "cr8-engine",
        "iat": now,
        "exp": now + ttl,
        "type": "blender-service",
    }
    token = jwt.encode(payload, _get_secret(), algorithm="HS256")
    logger.info(f"Generated internal token for Blender instance (user={username}, ttl={ttl}s)")
    return token


def validate_internal_token(token: str) -> dict:
    """
    Validate an internal HMAC-HS256 token from a Blender instance.

    Args:
        token: The raw JWT string from Socket.IO auth.

    Returns:
        Decoded claims dict (sub, iss, iat, exp, type).

    Raises:
        jwt.exceptions.PyJWTError: If the token is invalid, expired, or has wrong issuer.
    """
    claims = jwt.decode(
        token,
        _get_secret(),
        algorithms=["HS256"],
        issuer="cr8-engine",
        options={"require": ["exp", "iss", "sub", "type"]},
    )
    if claims.get("type") != "blender-service":
        raise jwt.InvalidTokenError("Token type is not 'blender-service'")
    return claims
