"""
SQLAlchemy models for the provisioning system's durable state — Postgres is
the source of truth (replaces the legacy unlocked flat-JSON state file).

Rows in provisioned_instances/teardown_intents are never hard-deleted; this
doubles as the audit trail the legacy system had none of.
"""

import uuid
from datetime import datetime

from sqlalchemy import String, Integer, BigInteger, DateTime, ForeignKey, func, UniqueConstraint, Index, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class ProvisionedInstance(Base):
    __tablename__ = "provisioned_instances"

    # autoincrement=False: this ID comes from VastAI, not generated by us —
    # a bare BigInteger PK otherwise gets an unused SERIAL sequence attached.
    vastai_instance_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=False)
    lifecycle_state: Mapped[str] = mapped_column(String, nullable=False)
    gpu_name: Mapped[str] = mapped_column(String, nullable=False)
    # The physical host — distinct from vastai_instance_id, which is the
    # ephemeral rental/contract. Recorded at launch so a fast launch can be
    # traced back to which machine it landed on (see FastLaunchMachine).
    machine_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True, index=True)
    host: Mapped[str | None] = mapped_column(String, nullable=True)
    ssh_port: Mapped[int | None] = mapped_column(Integer, nullable=True)
    max_users: Mapped[int] = mapped_column(Integer, nullable=False)

    # Raw VastAI signals, recorded verbatim on every poll.
    vastai_actual_status: Mapped[str | None] = mapped_column(String, nullable=True)
    vastai_cur_state: Mapped[str | None] = mapped_column(String, nullable=True)
    vastai_intended_status: Mapped[str | None] = mapped_column(String, nullable=True)
    vastai_next_state: Mapped[str | None] = mapped_column(String, nullable=True)

    last_polled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Updates only when the (actual_status, cur_state, next_state) tuple actually
    # changes — this is the input to progress-based stuck-detection, distinct
    # from wall-clock-since-created.
    last_state_change_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    phase_detail: Mapped[str | None] = mapped_column(String, nullable=True)  # current CR8:STATUS substep
    last_error_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    last_error_message: Mapped[str | None] = mapped_column(String, nullable=True)

    adopted: Mapped[bool] = mapped_column(default=False, nullable=False, server_default=text("false"))

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    destroyed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    sessions: Mapped[list["InstanceUserSession"]] = relationship(back_populates="instance")


class InstanceUserSession(Base):
    __tablename__ = "instance_user_sessions"
    __table_args__ = (
        # One active session per user — mirrors the legacy user_assignments model.
        Index(
            "ux_one_active_session_per_user",
            "username",
            unique=True,
            postgresql_where=text("ended_at IS NULL"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    vastai_instance_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("provisioned_instances.vastai_instance_id"), nullable=False
    )
    username: Mapped[str] = mapped_column(String, nullable=False, index=True)
    blender_pid: Mapped[int | None] = mapped_column(Integer, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    instance: Mapped["ProvisionedInstance"] = relationship(back_populates="sessions")


class TeardownIntent(Base):
    __tablename__ = "teardown_intents"
    __table_args__ = (
        Index(
            "ux_open_teardown_per_instance",
            "vastai_instance_id",
            unique=True,
            postgresql_where=text("status NOT IN ('confirmed_destroyed', 'confirmed_absent')"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    vastai_instance_id: Mapped[int] = mapped_column(BigInteger, nullable=False, index=True)
    reason: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending", server_default="pending")
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    next_attempt_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_error: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class ProvisioningEvent(Base):
    """Audit trail + timeout-tuning telemetry. Append-only."""
    __tablename__ = "provisioning_events"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    vastai_instance_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True, index=True)
    username: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    event_type: Mapped[str] = mapped_column(String, nullable=False)  # e.g. "state_transition", "teardown_enqueued"
    detail: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class FastLaunchMachine(Base):
    """Ledger of physical hosts (machine_id, not the ephemeral rental id) that
    have completed a full launch (offer accepted -> Blender fully up) at or
    under ProvisioningConfig.FAST_LAUNCH_THRESHOLD_SECONDS at least once.
    orchestrator.py's offer search tries these machines first, for the same
    GPU tier, before falling back to the general (geo-filtered) search — the
    goal is landing on the same known-fast host again whenever it's still
    available for rent, not just recording that it once was fast."""
    __tablename__ = "fast_launch_machines"

    machine_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=False)
    gpu_name: Mapped[str] = mapped_column(String, nullable=False, index=True)
    best_launch_seconds: Mapped[int] = mapped_column(Integer, nullable=False)
    fast_launch_count: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    last_vastai_instance_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    last_fast_launch_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
